In [5]:
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd

knn = KNeighborsClassifier(n_neighbors=3)
data = pd.read_table('fruit_data_with_colors.txt')

data.head()



fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79

In [4]:
X = data[['mass','height','width','color_score']]
y = data['fruit_label']
X.head()

mass  height  width  color_score
0   192     7.3    8.4         0.55
1   180     6.8    8.0         0.59
2   176     7.2    7.4         0.60
3    86     4.7    6.2         0.80
4    84     4.6    6.0         0.79

In [6]:
y.head()

0    1
1    1
2    1
3    2
4    2
Name: fruit_label, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y)
knn.fit(X_train,y_train)
knn.score(X_test,y_test)

0.8

In [8]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()

X_train = mm.fit_transform(X_train)
X_train

array([[0.28571429, 0.55555556, 0.52941176, 0.32432432],
       [0.42857143, 0.9047619 , 0.44117647, 0.45945946],
       [0.15714286, 0.6984127 , 0.05882353, 0.51351351],
       [1.        , 0.82539683, 1.        , 0.54054054],
       [0.34285714, 0.57142857, 0.38235294, 1.        ],
       [0.32857143, 0.57142857, 0.5       , 0.48648649],
       [0.39285714, 0.82539683, 0.41176471, 0.45945946],
       [0.01428571, 0.04761905, 0.02941176, 0.7027027 ],
       [0.14285714, 0.71428571, 0.08823529, 0.43243243],
       [0.03571429, 0.11111111, 0.11764706, 0.67567568],
       [0.2       , 0.74603175, 0.        , 0.48648649],
       [0.29285714, 0.6031746 , 0.41176471, 0.59459459],
       [0.33571429, 0.61904762, 0.52941176, 0.89189189],
       [0.35      , 0.96825397, 0.44117647, 0.45945946],
       [0.15      , 0.63492063, 0.02941176, 0.45945946],
       [0.30714286, 0.49206349, 0.5       , 0.75675676],
       [0.01428571, 0.04761905, 0.        , 0.59459459],
       [0.23571429, 0.6031746 ,

In [9]:
X_test = mm.transform(X_test)
X_test


array([[0.14285714, 0.55555556, 0.05882353, 0.45945946],
       [0.36428571, 0.6031746 , 0.38235294, 1.        ],
       [0.35714286, 0.50793651, 0.47058824, 0.13513514],
       [0.40714286, 0.65079365, 0.5       , 0.51351351],
       [0.31428571, 0.47619048, 0.41176471, 0.67567568],
       [0.34285714, 0.47619048, 0.47058824, 0.91891892],
       [0.15      , 0.65079365, 0.08823529, 0.40540541],
       [0.95      , 0.85714286, 0.94117647, 0.54054054],
       [0.32142857, 0.52380952, 0.32352941, 1.02702703],
       [0.45714286, 0.82539683, 0.5       , 0.59459459],
       [0.27857143, 0.50793651, 0.41176471, 0.72972973],
       [0.02857143, 0.0952381 , 0.05882353, 0.64864865],
       [1.02142857, 0.82539683, 1.11764706, 0.51351351],
       [0.44285714, 1.03174603, 0.44117647, 0.45945946],
       [0.28571429, 0.49206349, 0.55882353, 0.37837838]])

In [11]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)
knn.score(X_test,y_test)


0.8666666666666667

In [12]:
knn.predict(X_test)

array([4, 1, 1, 1, 3, 1, 4, 3, 1, 4, 3, 2, 3, 4, 1], dtype=int64)

In [13]:
y_test

51    4
8     1
2     1
33    3
32    3
9     1
58    4
24    3
10    1
27    3
42    3
4     2
26    3
44    4
15    1
Name: fruit_label, dtype: int64

In [16]:
from sklearn.neighbors import KNeighborsRegressor
knn = KNeighborsRegressor(n_neighbors=3)
from sklearn.datasets import load_boston
data = load_boston()
X, y = load_boston(return_X_y=True)

C:\Users\janat\anaconda\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i

In [17]:
X.shape


(506, 13)

In [18]:
y.shape


(506,)

In [19]:
print(load_boston()['DESCR'])

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y)
knn.fit(X_train,y_train)
knn.score(X_test,y_test)


0.6125447332263884